Capstone.Web/Models/ErrorViewModel.cs
// <copyright file="ErrorViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Capstone.Web.Models
{
    /// <summary>
    /// Represents the model for error information to be displayed in views. This model includes details about the error such as a request ID.
    /// </summary>
    public class ErrorViewModel
    {
        /// <summary>
        /// Gets or sets the unique identifier for the current HTTP request. This can be used to correlate the error with server logs.
        /// </summary>
        /// <value>The unique identifier of the HTTP request that resulted in an error.</value>
        public string? RequestId { get; set; }

        /// <summary>
        /// Gets a value indicating whether the request ID should be shown in the error view. This is determined based on the presence of a non-empty request ID.
        /// </summary>
        /// <value><c>true</c> if the request ID is not null or empty; otherwise, <c>false</c>.</value>
        public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
    }
}

Capstone.Web/Models/VMLogin.cs
namespace TodoListApp.WebApp.Models
{
    public class VMLogin
    {
        public string Email { get; set; }

        public string Password { get; set; }

        public bool KeepLoggedIn { get; set; }
    }
}

Capstone.Web/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using TodoListApp.WebApp.Models;

namespace TodoListApp.WebApp.Controllers
{
    public class AccessController : Controller
    {
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;

            if(claimUser.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VMLogin modelLogin)
        {
            if (modelLogin.Email == "user@example.com" && modelLogin.Password == "123")
            {
                List<Claim> claims = new List<Claim>() {
                new Claim(ClaimTypes.NameIdentifier, modelLogin.Email),
                new Claim("OtherProperties","Example Role")

                };

                ClaimsIdentity claimsidentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = modelLogin.KeepLoggedIn

                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsidentity), properties);

                return RedirectToAction("Index", "Home");
            }

            ViewData["ValidateMessage"] = "user not found";
            return View();
        }
    }
}

Capstone.Web/Controllers/AccountController.cs
// <copyright file="AccountController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TodoList.WebApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using TodoList.Services.WebApi.Services;
    using TodoList.WebApi.Models.Models;

    public class AccountController : Controller
    {
        private readonly AuthenticationService authenticationService;
        private readonly IHttpContextAccessor httpContextAccessor;

        public AccountController(AuthenticationService authenticationService, IHttpContextAccessor httpContextAccessor)
        {
            this.authenticationService = authenticationService;
            this.httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginView model)
        {
            if (this.ModelState.IsValid)
            {
                string token = await this.authenticationService.GetTokenAsync(model.Email, model.Password);
                if (token != null)
                {
                    var cookieOptions = new CookieOptions
                    {
                        HttpOnly = true,
                        Secure = true, // Set to true only if the request is over HTTPS
                        SameSite = SameSiteMode.None,
                    };

                    // Append the cookie to the response
                    this.httpContextAccessor.HttpContext.Response.Cookies.Append("token", token, cookieOptions);

                    return this.RedirectToAction("Index", "Home");
                }
                else
                {
                    this.ModelState.AddModelError(string.Empty, "Invalid username or password");
                }
            }

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            this.httpContextAccessor.HttpContext.Response.Cookies.Delete("token");

            return this.RedirectToAction("Account", "Login");
        }
    }
}

Capstone.Web/Controllers/HomeController.cs
// <copyright file="HomeController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Capstone.Web.Controllers
{
    using System;
    using System.Diagnostics;
    using Capstone.Web.Models;
    using Microsoft.AspNetCore.Mvc;
    using TodoList.Services.WebApi.Services;

    /// <summary>
    /// Controller responsible for handling requests for the home page and related actions within the application.
    /// </summary>
    public class HomeController : Controller
    {
        private readonly TodoListWebApiService todoListService;
        private readonly ILogger<HomeController> logger;
        private readonly IHttpContextAccessor contextAccessor;
        private readonly string token;

        /// <summary>
        /// Initializes a new instance of the <see cref="HomeController"/> class.
        /// </summary>
        /// <param name="logger">The logger used for logging information and errors.</param>
        public HomeController(ILogger<HomeController> logger, TodoListWebApiService todoListService, IHttpContextAccessor contextAccessor)
        {
            this.logger = logger;
            this.todoListService = todoListService;
            this.contextAccessor = contextAccessor;
            this.token = this.contextAccessor.HttpContext.Request.Cookies["token"];
        }

        public async Task<IActionResult> Index()
        {
            var todoLists = await this.todoListService.GetTodoListsAsync(this.token);
            return this.View(todoLists);
        }

        /// <summary>
        /// Serves the privacy policy view of the application.
        /// </summary>
        /// <returns>The privacy view.</returns>
        public IActionResult Privacy()
        {
            return this.View();
        }

        /// <summary>
        /// Serves the error view in case of an application error. This action is decorated with <see cref="ResponseCacheAttribute"/>
        /// to prevent caching of the error view.
        /// </summary>
        /// <returns>The error view populated with error details.</returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Capstone.Web/Controllers/TodoController.cs
// <copyright file="TodoController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TodoList.WebApp.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using TodoList.Services.WebApi.Services;

    /// <summary>
    /// The TodoController is responsible for handling HTTP requests related to Todo items.
    /// It interacts with the TodoListWebApiService to perform CRUD operations on Todo items.
    /// </summary>
    public class TodoController : Controller
    {
        private readonly TodoListWebApiService todoListService;

        /// <summary>
        /// Initializes a new instance of the <see cref="TodoController"/> class.
        /// </summary>
        /// <param name="todoListService">The TodoListWebApiService instance used for interacting with Todo items.</param>
        public TodoController(TodoListWebApiService todoListService)
        {
            this.todoListService = todoListService;
        }
    }
}

Capstone.Web/Views/Access/Login.cshtml
@model TodoListApp.WebApp.Models.VMLogin;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <form asp-controller="Access" asp-action="Login" method="post">
        <h1>Login</h1>
        <input type="email" placeholder="Email" asp-for="Email" />
        <input type="password" placeholder="password" asp-for="password" />

        <label>
            <input type="checkbox" asp-for="KeepLoggedIn" />
            Keep me Logged In
        </label>
        <button type="submit"></button>

        @if(ViewData["ValidateMessage"] != null)
        {
           <br />
           <br />
            <label>@ViewData["ValidateMessage"]</label>
        }
    </form>
</body>
</html>

Capstone.Web/Views/Home/Index.cshtml
@model List<TodoList.WebApi.Models.Models.TodoListModel>

<h1>To-Do Lists</h1>

<ul>
    @foreach (var todoItem in Model)
    {
        <li>@todoItem.Title asd</li>
    }
</ul>

Capstone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Capstone.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Capstone.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Capstone.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (Context.Request.Cookies.ContainsKey("token"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Capstone.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>